### ISSUE TITLE
Support for Prestashop 1.6

### ISSUE THREAD

**Issue by waltervargas** [prestapyt/prestapyt#27]
Hello, 

I've read in the source code, which is not supported the version 1.6 of prestashop. 

How I can help?

I have the next problem trying to sync OpenERP 7 with prestashop 1.6:

```
OpenERP Server Error

Client Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, **self.params)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1132, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/controllers/main.py", line 1120, in _call_kw
    return getattr(req.session.model(model), method)(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)


Server Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/usr/lib/pymodules/python2.7/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/usr/lib/pymodules/python2.7/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, *params)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/usr/lib/pymodules/python2.7/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/home/vagrant/addons/prestashoperpconnect/models/prestashop_model.py", line 116, in synchronize_metadata
    import_batch(session, model, backend_id)
  File "/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py", line 1014, in import_batch
    importer.run(filters=filters, **kwargs)
  File "/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py", line 183, in run
    record_ids = self._run_page(filters, **kwargs)
  File "/home/vagrant/addons/prestashoperpconnect/unit/import_synchronizer.py", line 191, in _run_page
    record_ids = self.backend_adapter.search(filters)
  File "/home/vagrant/addons/prestashoperpconnect/unit/backend_adapter.py", line 126, in search
    return api.search(self._prestashop_model, filters)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt-0.4.0-py2.7.egg/prestapyt/prestapyt.py", line 494, in search
    search(resource, options=options)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt-0.4.0-py2.7.egg/prestapyt/prestapyt.py", line 348, in search
    return self.get(resource, options=options)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt-0.4.0-py2.7.egg/prestapyt/prestapyt.py", line 516, in get
    response = super(PrestaShopWebServiceDict, self).get(resource, resource_id=resource_id, options=options)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt-0.4.0-py2.7.egg/prestapyt/prestapyt.py", line 366, in get
    return self.get_with_url(full_url)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt-0.4.0-py2.7.egg/prestapyt/prestapyt.py", line 536, in get_with_url
    response = super(PrestaShopWebServiceDict, self).get_with_url(url)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt-0.4.0-py2.7.egg/prestapyt/prestapyt.py", line 375, in get_with_url
    r = self._execute(url, 'GET')
  File "/usr/local/lib/python2.7/dist-packages/prestapyt-0.4.0-py2.7.egg/prestapyt/prestapyt.py", line 206, in _execute
    self._check_status_code(r.status_code, r.content)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt-0.4.0-py2.7.egg/prestapyt/prestapyt.py", line 144, in _check_status_code
    ps_error_code, ps_error_msg = self._parse_error(content)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt-0.4.0-py2.7.egg/prestapyt/prestapyt.py", line 116, in _parse_error
    error_answer = self._parse(xml_content)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt-0.4.0-py2.7.egg/prestapyt/prestapyt.py", line 619, in _parse
    parsed_content = super(PrestaShopWebServiceDict, self)._parse(content)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt-0.4.0-py2.7.egg/prestapyt/prestapyt.py", line 227, in _parse
    parsed_content = ElementTree.fromstring(unicode_encode.unicode2encoding(content))
  File "<string>", line 124, in XML
ParseError: syntax error: line 1, column 49
```

**Comment by pedrobaeza** [comment]
I think https://github.com/prestapyt/prestapyt/pull/34 can solve this.
