### ISSUE TITLE
Please help me, "No module named prestapyt" error

### ISSUE THREAD

**Issue by DanLaur** [prestapyt/prestapyt#30]
Hi, i'm not computer user expert, i have a problem for use connector-prestashop (https://github.com/OCA/connector-prestashop)

I use local prestashop 1.6 and local odoo 8. (use windows 8.1)
I have installed pyton 2.7
i have  installed easy install
i have installed pip install
i have copied folder prestapyt (unzipped from prestapty-master) inside C:\Python27\Scripts
i have installed prestapyt with comand C:\Python27\Scripts\pip.exe install Prestapyt
i have installed requirements.txt with comand C:\Python27\Scripts\pip.exe install requirements.txt -r
i have copied the 3 modules folders of prestashop-connector inside odoo addons

When i upgrade the modules in odoo setting - upgrade modules,
i have this error:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server.\openerp\http.py", line 530, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server.\openerp\http.py", line 567, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server.\openerp\http.py", line 303, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server.\openerp\http.py", line 300, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server.\openerp\http.py", line 796, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server.\openerp\http.py", line 396, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server\openerp\addons\web\controllers\main.py", line 940, in call_button
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server\openerp\addons\web\controllers\main.py", line 928, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server.\openerp\api.py", line 393, in old_api
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server.\openerp\api.py", line 397, in new_api
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server\openerp\addons\base\module\wizard\base_module_update.py", line 15, in update_module
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server.\openerp\api.py", line 239, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server.\openerp\api.py", line 462, in new_api
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server\openerp\addons\base\module\module.py", line 654, in update_list
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server.\openerp\http.py", line 1298, in load_addons
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server.\openerp\modules\module.py", line 80, in load_module
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server\openerp\addons\prestashoperpconnect__init__.py", line 27, in <module>
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server\openerp\addons\prestashoperpconnect\product.py", line 34, in <module>
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server\openerp\addons\prestashoperpconnect\unit__init__.py", line 26, in <module>
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server\openerp\addons\prestashoperpconnect\unit\mapper.py", line 35, in <module>
  File "C:\Program Files (x86)\Odoo 8.0-20150424\server\openerp\addons\prestashoperpconnect\unit\backend_adapter.py", line 29, in <module>

ImportError: No module named prestapyt

I don't know what's happen, PLEASE ANYONE CAN HELP ME???
THANKS

**Comment by tburon** [comment]
you can find the solution?

**Comment by JuanMuFe** [comment]
Please, give a solution for this...

**Comment by guewen** [comment]
Hi,

I don't know well how to use pip and python on Windows as I'm a GNU/Linux user. Still why couldn't you use `pip install prestapyt` so it installs from pypi?

**Comment by pymym213** [comment]
Hi,
(Nearly three years later :p) ... 
I recently got into the same problem, hope it helps someone else :

Try at first to install via `pip install prestapyt`.
If you have both python 2 and 3 installed, then use `pip2 install prestapyt` instead.
If it doesn't work, try to copy/past all files and folders (without overwriting) in `Python27\Lib\site-packages\` to `Odoo 8.0-20XXXXXX\server\Lib\site-packages\` or `Odoo 8.0-20XXXXXX\server\`.
