### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib.metadata'

### ISSUE THREAD

**Issue by Arian-SM** [prestapyt/prestapyt#68]
Hi
I just trying to working with this library for the first time and after installing the module in a virtual environment the above error raised and I do not know what to do for solving this problem

`(env) C:\Users\Arian-pc\Dropbox\Projects\update-price-rule-prestashop\app>python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from prestapyt import PrestaShopWebService
  File "C:\Users\Arian-pc\Dropbox\Projects\update-price-rule-prestashop\env\lib\site-packages\prestapyt\__init__.py", line 1, in <module>
    from .prestapyt import PrestaShopWebService
  File "C:\Users\Arian-pc\Dropbox\Projects\update-price-rule-prestashop\env\lib\site-packages\prestapyt\prestapyt.py", line 52, in <module>
    from .version import __author__
  File "C:\Users\Arian-pc\Dropbox\Projects\update-price-rule-prestashop\env\lib\site-packages\prestapyt\version.py", line 1, in <module>
    from importlib.metadata import version, PackageNotFoundError
ModuleNotFoundError: No module named 'importlib.metadata'`

I'm also read the famous topics in GitHub and StackOverflow but that doesn't help 
can you just tell me how can I solve this problem?
is it related to the python version ?

my python version is -> Python 3.7.4
 
I'm also installed "importlib-metadata" but it doesn't help

thank you

**Comment by pedrobaeza** [comment]
Duplicated of #62
