### ISSUE TITLE
HTTP response is empty

### ISSUE THREAD

**Issue by PengZhigang** [prestapyt/prestapyt#69]
hi 

i got this error when i wanted to add a product to the shop. my script works before. i did not change my script, but my shop update from 1.5 to 1.6.

can anyone help? thanks

**Comment by estresmo** [comment]
This library is outdated, if you want to add a product you must send with xml (not with dictionary). This work for me:`          product_xml = f"""
        <prestashop>
            <product>
                <id></id>
                <id_manufacturer></id_manufacturer>
                <id_supplier></id_supplier>
                <id_category_default></id_category_default>
                <new></new>
                <cache_default_attribute></cache_default_attribute>
                <id_default_image></id_default_image>
                <id_default_combination></id_default_combination>
                <id_tax_rules_group></id_tax_rules_group>
                <position_in_category></position_in_category>
                <type></type>
                <id_shop_default>1</id_shop_default>
                <reference>{product['reference']}</reference>
                <supplier_reference></supplier_reference>
                <location></location>
                <width></width>
                <height></height>
                <depth></depth>
                <weight></weight>
                <quantity_discount></quantity_discount>
                <ean13></ean13>
                <upc></upc>
                <cache_is_pack></cache_is_pack>
                <cache_has_attachments></cache_has_attachments>
                <is_virtual>1</is_virtual>
                <on_sale>1</on_sale>
                <state>1</state>
                <online_only></online_only>
                <ecotax></ecotax>
                <minimal_quantity>1</minimal_quantity>
                <price>{product['price']}</price>
                <wholesale_price></wholesale_price>
                <unity></unity>
                <unit_price_ratio></unit_price_ratio>
                <additional_shipping_cost></additional_shipping_cost>
                <customizable></customizable>
                <text_fields></text_fields>
                <uploadable_files></uploadable_files>
                <active>1</active>
                <redirect_type></redirect_type>
                <id_product_redirected></id_product_redirected>
                <available_for_order>1</available_for_order>
                <available_date></available_date>
                <condition></condition>
                <show_price>1</show_price>
                <indexed></indexed>
                <visibility>both</visibility>
                <advanced_stock_management></advanced_stock_management>
                <date_add></date_add>
                <date_upd></date_upd>
                <meta_description><language id='1'></language><language id='2'></language></meta_description>
                <meta_keywords><language id='1'></language><language id='2'></language></meta_keywords>
                <meta_title><language id='1'></language><language id='2'></language></meta_title>
                <link_rewrite><language id='1'></language><language id='2'></language></link_rewrite>
                <name><language id='1'>{product['name1']}</language><language id='2'>{product['name2']}</language></name>
                <description><language id='1'>{product['description1']}</language><language id='2'>{product['description2']}</language></description>
                <description_short><language id='1'>{product['descriptionshort1']}</language><language id='2'>{product['descriptionshort2']}</language></description_short>
                <available_now><language id='1'>1</language><language id='2'></language></available_now>
                <available_later><language id='1'></language><language id='2'></language></available_later>
            <associations>
            <categories>
                <category>
                <id></id>
                </category>
            </categories>
            <images>
                <image>
                <id></id>
                </image>
            </images>
            <combinations>
                <combination>
                <id></id>
                </combination>
            </combinations>
            <product_option_values>
                <product_option_value>
                <id></id>
                </product_option_value>
            </product_option_values>
            <product_features>
                <product_feature>
                <id></id>
                <id_feature_value></id_feature_value>
                </product_feature>
            </product_features>
            <tags>
                <tag>
                <id></id>
                </tag>
            </tags>
            <stock_availables>
                <stock_available>
                <id></id>
                <id_product_attribute></id_product_attribute>
                </stock_available>
            </stock_availables>
            <accessories>
                <product>
                <id></id>
                </product>
            </accessories>
            </associations>
            </product>
        </prestashop>"""

prestashop.add('products', product_xml)
`  
and for add image 
`        
product = self.prestashop.search('products', options={'filter[reference]': '[' + product['reference'] + ']'})
        root = product[0][0].attrib
        product_id=root['id']
        for image in images:
            file_name = image
            fd = io.open(file_name, "rb")
            content = fd.read()
            fd.close()
            self.prestashop.add('/images/products/' + product_id, files=[('image', file_name, content)])
            print('SENT:' + image)
        print('DONE:')
`

**Comment by PengZhigang** [comment]
thank you, i'll try it.

**Comment by PengZhigang** [comment]
> This library is outdated, if you want to add a product you must send with xml (not with dictionary). This work for me:
> 
> ```
>  product_xml = f"""
>         <prestashop>
>             <product>
>                 <id></id>
>                 <id_manufacturer></id_manufacturer>
>                 <id_supplier></id_supplier>
>                 <id_category_default></id_category_default>
>                 <new></new>
>                 <cache_default_attribute></cache_default_attribute>
>                 <id_default_image></id_default_image>
>                 <id_default_combination></id_default_combination>
>                 <id_tax_rules_group></id_tax_rules_group>
>                 <position_in_category></position_in_category>
>                 <type></type>
>                 <id_shop_default>1</id_shop_default>
>                 <reference>{product['reference']}</reference>
>                 <supplier_reference></supplier_reference>
>                 <location></location>
>                 <width></width>
>                 <height></height>
>                 <depth></depth>
>                 <weight></weight>
>                 <quantity_discount></quantity_discount>
>                 <ean13></ean13>
>                 <upc></upc>
>                 <cache_is_pack></cache_is_pack>
>                 <cache_has_attachments></cache_has_attachments>
>                 <is_virtual>1</is_virtual>
>                 <on_sale>1</on_sale>
>                 <state>1</state>
>                 <online_only></online_only>
>                 <ecotax></ecotax>
>                 <minimal_quantity>1</minimal_quantity>
>                 <price>{product['price']}</price>
>                 <wholesale_price></wholesale_price>
>                 <unity></unity>
>                 <unit_price_ratio></unit_price_ratio>
>                 <additional_shipping_cost></additional_shipping_cost>
>                 <customizable></customizable>
>                 <text_fields></text_fields>
>                 <uploadable_files></uploadable_files>
>                 <active>1</active>
>                 <redirect_type></redirect_type>
>                 <id_product_redirected></id_product_redirected>
>                 <available_for_order>1</available_for_order>
>                 <available_date></available_date>
>                 <condition></condition>
>                 <show_price>1</show_price>
>                 <indexed></indexed>
>                 <visibility>both</visibility>
>                 <advanced_stock_management></advanced_stock_management>
>                 <date_add></date_add>
>                 <date_upd></date_upd>
>                 <meta_description><language id='1'></language><language id='2'></language></meta_description>
>                 <meta_keywords><language id='1'></language><language id='2'></language></meta_keywords>
>                 <meta_title><language id='1'></language><language id='2'></language></meta_title>
>                 <link_rewrite><language id='1'></language><language id='2'></language></link_rewrite>
>                 <name><language id='1'>{product['name1']}</language><language id='2'>{product['name2']}</language></name>
>                 <description><language id='1'>{product['description1']}</language><language id='2'>{product['description2']}</language></description>
>                 <description_short><language id='1'>{product['descriptionshort1']}</language><language id='2'>{product['descriptionshort2']}</language></description_short>
>                 <available_now><language id='1'>1</language><language id='2'></language></available_now>
>                 <available_later><language id='1'></language><language id='2'></language></available_later>
>     
>      <associations>
>             <categories>
>                 <category>
>                 <id></id>
>                 </category>
>             </categories>
>             <images>
>                 <image>
>                 <id></id>
>                 </image>
>             </images>
>             <combinations>
>                 <combination>
>                 <id></id>
>                 </combination>
>             </combinations>
>             <product_option_values>
>                 <product_option_value>
>                 <id></id>
>                 </product_option_value>
>             </product_option_values>
>             <product_features>
>                 <product_feature>
>                 <id></id>
>                 <id_feature_value></id_feature_value>
>                 </product_feature>
>             </product_features>
>             <tags>
>                 <tag>
>                 <id></id>
>                 </tag>
>             </tags>
>             <stock_availables>
>                 <stock_available>
>                 <id></id>
>                 <id_product_attribute></id_product_attribute>
>                 </stock_available>
>             </stock_availables>
>             <accessories>
>                 <product>
>                 <id></id>
>                 </product>
>             </accessories>
>             </associations>
>             </product>
>         </prestashop>"""
> prestashop.add('products', product_xml)
> ```
> 
> and for add image
> 
> ```
> product = self.prestashop.search('products', options={'filter[reference]': '[' + product['reference'] + ']'})
>         root = product[0][0].attrib
>         product_id=root['id']
>         for image in images:
>             file_name = image
>             fd = io.open(file_name, "rb")
>             content = fd.read()
>             fd.close()
>             self.prestashop.add('/images/products/' + product_id, files=[('image', file_name, content)])
>             print('SENT:' + image)
>         print('DONE:')
> ```

i got this     
 prestapyt\prestapyt.py", line 162, in _parse_error  code = error.find('code').textAttributeError: 'NoneType' object has no attribute 'text'

i have no idea where it is form.

**Comment by vgascon** [comment]
### Problem:
Hi! I had the same problem in **Prestashop 8.0.1** with the **multi-language** configuration, so I enabled Prestashop debugging and got this: 

```
Fatal error: Uncaught InvalidArgumentException: "" cannot be interpreted as a number in
/bitnami/prestashop/vendor/prestashop/decimal/src/Builder.php:36
Stack trace:
#0 /bitnami/prestashop/vendor/prestashop/decimal/src/DecimalNumber.php(73): PrestaShop\Decimal\Builder::parseNumber()
#1 /bitnami/prestashop/classes/Product.php(887): PrestaShop\Decimal\DecimalNumber->__construct()
#2 /bitnami/prestashop/classes/Product.php(853): ProductCore->fillUnitRatio()
#3 /bitnami/prestashop/classes/Product.php(805): ProductCore->updateUnitRatio()
#4 /bitnami/prestashop/classes/Product.php(7554): ProductCore->add()
#5 /bitnami/prestashop/classes/webservice/WebserviceRequest.php(1669): ProductCore->addWs()
#6 /bitnami/prestashop/classes/webservice/WebserviceRequest.php(1444): WebserviceRequestCore->saveEntityFromXml()
#7 /bitnami/prestashop/classes/webservice/WebserviceRequest.php(579): WebserviceRequestCore->executeEntityPost()
#8 /bitnami/prestashop/webservice/dispatcher.php(90): WebserviceRequestCore->fetch()
#9 {main}
thrown in /bitnami/prestashop/vendor/prestashop/decimal/src/Builder.php on line 36
```

### Fix:
In my case, I could determine that the dictionary was missing the **unit_price** and **unit_price_ratio** fields, as Prestashop was complaining about receiving an empty field "" on line 887. (In previous versions of Prestashop, only the price field was sent).

In the end, everything turned out fine. For now, we have been able to continue using dictionaries instead of raw XML. Maybe you should try something similar.

**Comment by AzadGh95** [comment]
> ### Problem:
> Hi! I had the same problem in **Prestashop 8.0.1** with the **multi-language** configuration, so I enabled Prestashop debugging and got this:
> 
> ```
> Fatal error: Uncaught InvalidArgumentException: "" cannot be interpreted as a number in
> /bitnami/prestashop/vendor/prestashop/decimal/src/Builder.php:36
> Stack trace:
> #0 /bitnami/prestashop/vendor/prestashop/decimal/src/DecimalNumber.php(73): PrestaShop\Decimal\Builder::parseNumber()
> #1 /bitnami/prestashop/classes/Product.php(887): PrestaShop\Decimal\DecimalNumber->__construct()
> #2 /bitnami/prestashop/classes/Product.php(853): ProductCore->fillUnitRatio()
> #3 /bitnami/prestashop/classes/Product.php(805): ProductCore->updateUnitRatio()
> #4 /bitnami/prestashop/classes/Product.php(7554): ProductCore->add()
> #5 /bitnami/prestashop/classes/webservice/WebserviceRequest.php(1669): ProductCore->addWs()
> #6 /bitnami/prestashop/classes/webservice/WebserviceRequest.php(1444): WebserviceRequestCore->saveEntityFromXml()
> #7 /bitnami/prestashop/classes/webservice/WebserviceRequest.php(579): WebserviceRequestCore->executeEntityPost()
> #8 /bitnami/prestashop/webservice/dispatcher.php(90): WebserviceRequestCore->fetch()
> #9 {main}
> thrown in /bitnami/prestashop/vendor/prestashop/decimal/src/Builder.php on line 36
> ```
> 
> ### Fix:
> In my case, I could determine that the dictionary was missing the **unit_price** and **unit_price_ratio** fields, as Prestashop was complaining about receiving an empty field "" on line 887. (In previous versions of Prestashop, only the price field was sent).
> 
> In the end, everything turned out fine. For now, we have been able to continue using dictionaries instead of raw XML. Maybe you should try something similar.

How did you enable **Prestashop debugging**?

**Comment by AzadGh95** [comment]
And this is how to enable Debugging Mood.
https://help-center.prestashop.com/en/articles/9242063447698-debug-mode
